In [ ]:
#1.What is a python library?Why do we use python libraries


#A Python library is a collection of pre-written code (functions, classes, modules, etc.) that developers can use to perform specific tasks without having to implement the functionality from scratch.
#These libraries are created to provide reusable and well-tested solutions to common programming problems.
#Python libraries are used for various reasons, including:


#1.Code Reusability: Libraries allow developers to reuse existing code rather than writing it from scratch. This saves time and effort, as developers can leverage the functionality provided by the library to perform complex tasks quickly.

#2.Increased Productivity: By using libraries, developers can focus on solving higher-level problems rather than getting bogged down in the details of low-level implementation. This leads to increased productivity and faster development cycles.

#3.Modularity: Libraries promote modular programming by providing a way to organize code into separate components. This makes the codebase easier to maintain, debug, and extend over time.

#4.Community Support: Many Python libraries are open-source and have large communities of developers contributing to their development and maintenance. This means that libraries often have extensive documentation, tutorials, and support forums available, making it easier for developers to learn and use them effectively.

#5.Performance Optimization: Python libraries are often written in C or C++ for performance-critical tasks, which can significantly improve the execution speed of Python programs.


In [ ]:
#2.what is the difference between numpy array and list


#1.Data Type:
#NumPy arrays are homogeneous, meaning they contain elements of the same data type. This allows for more efficient storage and computation, especially for numerical data.
#Python lists are heterogeneous, meaning they can contain elements of different data types. This flexibility comes at the cost of reduced performance and memory efficiency compared to NumPy arrays.

#2.Memory Efficiency:
#NumPy arrays are more memory efficient compared to Python lists. Since NumPy arrays are homogeneous, they require less memory overhead for storing elements.
#Python lists have more memory overhead due to the additional information required to store heterogeneous elements and support dynamic resizing.

#3.Performance:
#NumPy arrays provide faster computation for numerical operations compared to Python lists. NumPy operations are implemented in compiled C code, leading to optimized performance.
#Python lists are slower for numerical computations, especially when iterating over elements, due to the dynamic typing and interpretation overhead.

#4.Functionality:
#NumPy arrays offer a wide range of mathematical functions and operations, such as element-wise operations, linear algebra, statistical functions, and Fourier transforms. These functions are optimized for performance and are not available for Python lists.
#Python lists provide more flexibility in terms of data storage and manipulation. They support dynamic resizing, appending, slicing, and other operations, but lack specialized numerical functions available in NumPy arrays.

#5.Syntax and Expressiveness:
#NumPy arrays have a more concise and expressive syntax for performing mathematical operations and working with multi-dimensional data. This makes them well-suited for numerical and scientific computing tasks.
#Python lists have a simpler syntax and are more intuitive for general-purpose programming and tasks that do not involve heavy numerical computation.



In [1]:
#3.find the shhape,size and dimension of the following array
#[[1,2,3,4]
#[5,6,7,8],
#[9,10,11,12]]

#It seems there's a formatting issue with the array you provided. In Python, each row of a 2D array should be enclosed in square brackets and separated by commas. Let me correct the formatting:

arr = [[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 10, 11, 12]]

import numpy as np

np_arr = np.array(arr)
shape = np_arr.shape
size = np_arr.size
dimension = np_arr.ndim

print("Shape of the array:", shape)
print("Size of the array:", size)
print("Dimension of the array:", dimension)


Shape of the array: (3, 4)
Size of the array: 12
Dimension of the array: 2


In [2]:
#4.write python code to access the first row of the following array?
#[[1,2,3,4]
#[5,6,7,8],
#[9,10,11,12]]

arr = [[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 10, 11, 12]]

first_row = arr[0]

print("First row of the array:", first_row)




First row of the array: [1, 2, 3, 4]


In [3]:
#5.how do you access the element at the third row and forth column from the given numpy array?
#[[1,2,3,4]
#[5,6,7,8],
#[9,10,11,12]]

import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

element = arr[2, 3]

print("Element at the third row and fourth column:", element)



Element at the third row and fourth column: 12


In [4]:
#6.write code to extract all odd-indexed element from the given numpy array?
#[[1,2,3,4]
#[5,6,7,8],
#[9,10,11,12]]


import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

odd_indexed_elements = arr[:, 1::2]

print("Odd-indexed elements:")
print(odd_indexed_elements)


Odd-indexed elements:
[[ 2  4]
 [ 6  8]
 [10 12]]


In [5]:
#7.how can you generate a random 3*3 matrix with values between 0 and 1?

import numpy as np

random_matrix = np.random.rand(3, 3)

print("Random 3x3 matrix:")
print(random_matrix)



Random 3x3 matrix:
[[0.01201434 0.69622722 0.74013359]
 [0.66019229 0.39701938 0.73911856]
 [0.15665222 0.10747875 0.75438544]]


In [6]:
#8.describe the difference between np.random.rand. and np.random.randn?

#1.np.random.rand():
#I.This function generates random numbers from a uniform distribution over the range [0, 1).
#II.The shape of the output array is specified as arguments to the function.
#III.Each element in the output array is an independent random number uniformly distributed between 0 and 1.
#IV.The function takes the dimensions of the desired array as input parameters.

#2.np.random.randn():
#I.This function generates random numbers from a standard normal distribution (mean=0, standard deviation=1).
#II.The shape of the output array is specified as arguments to the function.
#III.Each element in the output array is an independent random number drawn from a standard normal distribution.
#IV.The function takes the dimensions of the desired array as input parameters.

#In summary:
#np.random.rand() generates random numbers from a uniform distribution over [0, 1), and you specify the array shape.
#np.random.randn() generates random numbers from a standard normal distribution (mean=0, standard deviation=1), and you specify the array shape.

import numpy as np

rand_matrix = np.random.rand(2, 2)
randn_matrix = np.random.randn(2, 2)

print("Random matrix from uniform distribution:")
print(rand_matrix)

print("\nRandom matrix from standard normal distribution:")
print(randn_matrix)



Random matrix from uniform distribution:
[[0.5283912  0.64897844]
 [0.89515779 0.74656108]]

Random matrix from standard normal distribution:
[[ 0.4453011   0.62747631]
 [-1.23358047  0.87435775]]


In [7]:
#9.write code to increase the dimension of the following array?
#[[1,2,3,4]
#[5,6,7,8],
#[9,10,11,12]]

import numpy as np

arr = [[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 10, 11, 12]]

np_arr = np.array(arr)
expanded_arr = np.expand_dims(np_arr, axis=0)

print("Original array shape:", np_arr.shape)
print("Expanded array shape:", expanded_arr.shape)

#np.expand_dims(np_arr, axis=0) adds an additional axis at position 0, effectively increasing the dimension of the array. This results in an array with shape (1, 3, 4).
#axis=0 specifies the position along which the new axis will be added. In this case, it's added at the beginning, making the shape (1, 3, 4).


Original array shape: (3, 4)
Expanded array shape: (1, 3, 4)


In [8]:
#10.how to transpose the following array in numpy
#[[1,2,3,4]
#[5,6,7,8],
#[9,10,11,12]]

import numpy as np
arr = [[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 10, 11, 12]]

np_arr = np.array(arr)

transposed_arr = np.transpose(np_arr)

print("Original array:")
print(np_arr)
print("\nTransposed array:")
print(transposed_arr)



Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed array:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [9]:
#11.User
#consider the following matrix
#matrix A:[[1,2,3,4][5,6,7,8],[9,10,11,12]]
#matrix B:[[1,2,3,4],[5,6,7,8],[9,10,11,12]]

#perform the following operation using python
#1.index wise numtiplication
#2.matrix multiplication
#3.add both the maatric
#4.subtract matrix B from A
#5.divide mtrix B by A


import numpy as np

A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

B = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])


index_wise_multiplication = A * B

matrix_multiplication = np.dot(A, B.T)

matrix_addition = A + B

matrix_subtraction = A - B

A_with_epsilon = np.where(A == 0, 1e-15, A)
matrix_division = B / A_with_epsilon

print("Index-wise multiplication:")
print(index_wise_multiplication)

print("\nMatrix multiplication:")
print(matrix_multiplication)

print("\nMatrix addition:")
print(matrix_addition)

print("\nMatrix subtraction:")
print(matrix_subtraction)

print("\nMatrix division:")
print(matrix_division)


Index-wise multiplication:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

Matrix multiplication:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

Matrix addition:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Matrix subtraction:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Matrix division:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
#12.which function in numpy can be used to swap the byte order of an array

import numpy as np

arr = np.array([1, 2, 3, 4], dtype=np.int32)

arr_swapped = arr.byteswap()

print("Original array:", arr)
print("Array with swapped byte order:", arr_swapped)



Original array: [1 2 3 4]
Array with swapped byte order: [16777216 33554432 50331648 67108864]


In [11]:
#13.what is the significance of the np.linalg.inv function

#The np.linalg,inv function in numpy is used to compute the inverse of a square matrix.
#The inverse of a matrix A is another matrix,denoted as A-1,such that the product of A and its inverse A-1 equals the identity matrix I.
#In other words,A.A-1 = A-1.A=I

#The significance of np.linalg.inv lies in its application in various mathematical and computational problems, including:

#1.Solving Linrar Systems:
#The inverse of a matrix can be used to solve systems of linear equations of the form Ax=b,where A is a coefficient matrix,x is the vector of unknowns,and b is the right-hand side vector.
#The solution can be obtained as x = A-1.n.

#2.Computing Determinants: The determinant of a matrix can be computed using the inverse. Specifically,
#det,(A) = 1/det(A-1).

#3.Eigenvalue and Eigenvector Computations: Eigenvalues and eigenvectors of a matrix can be computed using its inverse in certain contexts.

#4.Numerical Stability: In some numerical algorithms, it may be more numerically stable to compute the inverse of a matrix explicitly rather than solving linear systems directly.


In [12]:
#14.what does the np.reshape function do, and how is it used?

#The np.reshape function takes the following parameters:

#a: The array to be reshaped.
#newshape: The new shape of the array, specified as a tuple of integers representing the dimensions of the new array.

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

reshaped_arr = np.reshape(arr, (2, 3))

print("Original array:")
print(arr)

print("\nReshaped array:")
print(reshaped_arr)



Original array:
[1 2 3 4 5 6]

Reshaped array:
[[1 2 3]
 [4 5 6]]


In [13]:
#15.what is broadcasting is numpy

#Broadcasting is a powerful feature in NumPy that allows arrays with different shapes to be combined or operated upon together.
#When performing operations on arrays with different shapes, NumPy automatically broadcasts the arrays to make their shapes compatible, without the need for explicit looping.

#The broadcasting rules in NumPy are as follows:
#If the arrays have different numbers of dimensions, the shape of the array with fewer dimensions is padded with ones on its left side.
#If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
#If in any dimension the sizes disagree and neither is equal to 1, an error is raised.


import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

result = a + b

print(result)


[[11 22 33]
 [14 25 36]]
